### ISSUE TITLE
@LTOMLengthOf Failing Testcase

### ISSUE THREAD

**Issue by ovshake** [kelloggm/checker-framework#142] opened 2017-03-25 09:47 UTC
Considering the following code
```
import org.checkerframework.checker.index.qual.*;

class IndexTest{
	public static void main(String[] args) {
		String[] name = {"a","b","c","d"};
		
		for(@LTOMLengthOf("name") int i = 0; i<name.length ; i++)
			name[i] = name[i+1];
		
	}
}

```

This should have thrown some error but it compiled successfully as at a particular the variable i was equal to 3. Is this how it should be done or am I making a mistake?

**Comment by mernst** [comment] 2017-03-25 17:52
This is a genuine problem.  It's a duplicate of issue #135.  I'm closing it in favor of that one.

**Closed by mernst** 2017-03-25 17:52 UTC
