### ISSUE TITLE
Interaction between @SameLen and @LTLengthOf

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#134] opened 2017-03-18 21:23 UTC
Consider this code, in which the two `format` methods are very similar.

```java
// Test interaction between SameLen and LTLengthOf

import org.checkerframework.checker.index.qual.SameLen;

public class SameLenLTL {

    static final class PptTopLevel {
        final String[] var_infos;

        PptTopLevel(String[] var_infos) {
            this.var_infos = var_infos;
        }
    }

    static final class Invocation1 {
        PptTopLevel ppt;
        Object @SameLen({"vals1", "ppt.var_infos"}) [] vals1;

        void format1() {
            for (int j = 0; j < vals1.length; j++) {
                System.out.println(ppt.var_infos[j]);
            }
        }
    }

    static final class Invocation2 {
        Object @SameLen({"vals2", "mods2"}) [] vals2;
        int @SameLen({"vals2", "mods2"}) [] mods2;

        void format2() {
            for (int j = 0; j < vals2.length; j++) {
                System.out.println(mods2[j]);
            }
        }
    }
}
```

`format1` does not typecheck, but `format2` does.  Here is the type-checker output:

```
$ch/bin/javac -g SameLenLTL.java -processor index
SameLenLTL.java:21: error: [array.access.unsafe.high] Potentially unsafe array access: the index could be larger than the array's bound
                System.out.println(ppt.var_infos[j]);
                                                 ^
  found   : @LTLengthOf(value="this.vals1", offset="0") int
  required: an integer less than this.ppt.var_infos's length (@LTLengthOf("this.ppt.var_infos"))
1 error
```

**Comment by kelloggm** [comment] 2017-03-21 21:06
The problem here is that we don't propagate SameLens when a variable is declared. I'm working on a fix.

**Comment by kelloggm** [comment] 2017-03-21 23:38
I was wrong about what the problem here is. I think it is due to a combination of a viewpoint adaptation issue and some missing things in the upper bound checker.

Here's a simplified test case:
```java
import org.checkerframework.checker.index.qual.*;

class SameLenWithObjects {

    class SimpleCollection {
        Object[] var_infos;
    }

    static final class Invocation1 {
        SimpleCollection sc;
        Object @SameLen({"vals1", "sc.var_infos"}) [] vals1;

        void format1() {
            for (int j = 0; j < vals1.length; j++) {
                System.out.println(sc.var_infos[j]);
            }
        }
    }
}
```
To solve the problem, I added code to the UBC so that SameLen annotations are checked when `array.length` expressions are typed (i.e. if `array` is `@SameLen({"a", "b"})`, then `array.length` becomes `@LTLengthOf({"array", "a", "b"})`. I'll PR that change, since it's something we ought to be doing anyway.

However, even with that change the simplified version doesn't typecheck. But, if you change `Object @SameLen({"vals1", "sc.var_infos"}) [] vals1;` to `Object @SameLen({"vals1", "this.sc.var_infos"}) [] vals1;` (note the added `this`), then no warning is issued. This might be a duplicate of #133

**Comment by kelloggm** [comment] 2017-03-29 20:47
The original test from this passes in typetools/master. I'm going to close this issue, and I'll merge the passing test into master once I verify that it passes on Travis as well as my local machine.

**Closed by kelloggm** 2017-03-29 20:47 UTC
