### ISSUE TITLE
Test against -1 should refine @GTENegativeOne to @NonNegative

### ISSUE THREAD

**Issue by mernst** [kelloggm/checker-framework#58] opened 2016-12-10 22:47 UTC
Here is a test case:

```java
  public static String replaceString(String target, String oldStr, String newStr) {
    if (oldStr.equals("")) {
      throw new IllegalArgumentException();
    }

    StringBuffer result = new StringBuffer();
    int lastend = 0;
    int pos;
    while ((pos = target.indexOf(oldStr, lastend)) != -1) {
      result.append(target.substring(lastend, pos));
      result.append(newStr);
      lastend = pos + oldStr.length();
    }
    result.append(target.substring(lastend));
    return result.toString();
  }
```

The checker can't tell that pos is `@NonNegative`.  The checker issues this warning:

```
warning: [argument.type.incompatible] incompatible types in argument.
      result.append(target.substring(lastend, pos));
                                              ^
  found   : @GTENegativeOne int
  required: @NonNegative int
```

**Comment by kelloggm** [comment] 2016-12-15 22:09
I can't reproduce this. I checked in your test in 8ae1ceb454c78ce6f2f95c190af790c852462f69 and it was passing. In particular, this issue is a duplicate of https://github.com/kelloggm/checker-framework/issues/29, which I fixed before.

**Comment by kelloggm** [comment] 2016-12-15 23:36
And yet the test I checked in is failing on travis

**Comment by kelloggm** [comment] 2016-12-16 23:58
So the problem here is actually quite insidious, I think. I've determined that we're correctly identifying that the expression "pos = target.indexOf(oldStr, lastend))" is of type GTEN1 and is being compared to -1, so it should be refined to NonNegative inside the then block. However, that refinement happens in the transfer function, and it doesn't seem to propagate to the subexpression. What this means is that "pos = target.indexOf(oldStr, lastend))" is a valid index, but "pos" is not, even though we _know_ that they're the same; we just don't learn it early enough to make use of it. I have no idea what the actual solution to this is.

**Comment by mernst** [comment] 2016-12-19 03:22
The dataflow framework can deal with this sort of construct.  It properly typechecks the below code (which is similar to what appears in method `while_set_and_test` in file `checker/tests/nullness/Flow.java`).  I wonder what is different between what the Nullness Checker does and what the Index Checker does, with respect to dataflow refinement.

```java
import java.io.*;
import org.checkerframework.checker.nullness.qual.NonNull;

public class AssignmentRefinement {

  private void demoA(BufferedReader reader) throws IOException {
    String line = null;
    while ((line = reader.readLine()) != null) {
      @NonNull String nn = line;
    }
  }
  
}
```

**Closed** 2017-03-21 23:58 UTC
