### ISSUE TITLE
Upper bound of modulo

### ISSUE THREAD

**Issue by panacekcz** [kelloggm/checker-framework#218] opened 2018-01-26 13:38 UTC
A modulo operation can be used to reduce an integer to a index, forexample `a[i%a.length]`.
- if `b` is `@NonNegative`, then `a%b < b` 
- if `a` is `@NonNegative`, then `a%b <= a` 

The upper bound checker should apply these rules:

- if `b` is `@NonNegative` and `@LTLengthOf(value, offset)` , then `a%b`  is `@LTLengthOf(value, offset + 1)` 
- if `a` is `@NonNegative` and `@LTLengthOf(value, offset)` , then `a%b`  is `@LTLengthOf(value, offset)` 
- if both of the above hold, take the glb of those

Code:
```java
import org.checkerframework.checker.index.qual.IndexFor;
import org.checkerframework.checker.index.qual.IndexOrHigh;
import org.checkerframework.checker.index.qual.NonNegative;

public class Modulo {
	void m1(Object[] a, @IndexOrHigh("#1") int i, @NonNegative int j) {
		@IndexFor("a") int k = j % i;
	}
	void m2(Object[] a, @NonNegative int i, @IndexFor("#1") int j) {
		@IndexFor("a") int k = j % i;
	}
}
```
Output:
```
Modulo.java:7: error: [assignment.type.incompatible] incompatible types in assignment.
		@IndexFor("a") int k = j % i;
		                         ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf(value="a", offset={}) int
/home/vlasta/workspace/CFExperiments/src/Modulo.java:10: error: [assignment.type.incompatible] incompatible types in assignment.
		@IndexFor("a") int k = j % i;
		                         ^
  found   : @UpperBoundUnknown int
  required: @LTLengthOf(value="a", offset={}) int
2 errors
```
Expeced: no warnings.

**Comment by panacekcz** [comment] 2018-01-26 15:10
I am fixing this.

**Comment by kelloggm** [comment] 2018-01-26 16:35
This is a duplicate of #195. Since @panacekcz is already assigned to this one and the test case in this one is more complete, I'll close that one in favor of this one.

**Comment by panacekcz** [comment] 2018-01-26 16:57
Sorry, I didn't find that one. Will that fix some false positives in your repositories?

**Comment by kelloggm** [comment] 2018-01-26 16:58
Yes. About 8 in JFreeChart.

**Closed** 2018-01-28 19:58 UTC
