### ISSUE TITLE
Types not being transferred in the presence of generics?

### ISSUE THREAD

**Issue by kelloggm** [kelloggm/checker-framework#106] opened 2017-02-24 19:58 UTC
Consider the following testcase:

```java
import org.checkerframework.checker.index.qual.*;

class ArrayLength4<T> {

   void test(String[] a, String[] b) {
        Object result = new Object[a.length + b.length];
	System.arraycopy(a, 0, result, 0, a.length);
    }
    
    void test2(String[] a, String[] b) {
	@SuppressWarnings("unchecked")
        T[] result = (T[]) new Object[a.length + b.length];
	System.arraycopy(a, 0, result, 0, a.length);
    }
}
```

The first function (`test`) compiles with no warnings, but the second function (`test2`) does not. The only difference is the addition of the cast to a generic argument, but the second function issues the following warning:

```java
ArrayLength4.java:8: error: [argument.type.incompatible] incompatible types in argument.
	System.arraycopy(a, 0, result, 0, a.length);
	                                   ^
  found   : @LTEqLengthOf("a") int
  required: @LTLengthOf(value={"a", "result"}, offset={"0 - 1", "0 - 1"}) int
```

The warning indicates that the transfer, when result is created, that should make `a` LTEL of `result` isn't happening. But it ought to, since `b.length` is certainly `NonNegative`

**Comment by smillst** [comment] 2017-02-24 20:04
The problem is the cast.  UpperBoundTransfer#visitAssignment is looking for the right hand side of the assignment to be an ArrayCreationNode, but instead it's a TypeCastNode.  We can change UBT to look for this case, too.

**Comment by kelloggm** [comment] 2017-02-25 00:15
typetools#1082 fixes this

**Comment by smillst** [comment] 2017-02-27 22:15
fixed via https://github.com/typetools/checker-framework/commit/2611c3160312aa1fd88084cadb05700703e4f8ef

**Closed by smillst** 2017-02-27 22:15 UTC
