### ISSUE TITLE
SameLen inference for custom collections

### ISSUE THREAD

**Issue by panacekcz** [kelloggm/checker-framework#194] opened 2017-11-27 10:19 UTC
When annotating a custom collection as in typetools#1680, `@SameLen` is not inferred after comparing lengths of two collections.

Code adapted from Guava:
```java
import org.checkerframework.checker.index.qual.IndexFor;
import org.checkerframework.checker.index.qual.LengthOf;

class Custom{
	public @LengthOf("this") int length() {
		throw new RuntimeException();
	}
	public Object get(@IndexFor("this") int i) {
		return null;
	}
}

public class CustomSamelen {
	public boolean m(Custom a, Custom b) {
		if(a.length() != b.length()) {
			return false;
		}
		for(int i=0;i<a.length();++i) {
			if(a.get(i)!=b.get(i))
				return false;
		}
		return true;
	}
}
```

Output:
```
CustomSamelen.java:19: error: [argument.type.incompatible] incompatible types in argument.
			if(a.get(i)!=b.get(i))
			                   ^
  found   : @LTLengthOf(value="a", offset="0") int
  required: @LTLengthOf(value="b", offset={}) int
1 error
```

Expected: no warnings. (Works when using arrays instead of a custom collection.)

**Comment by kelloggm** [comment] 2018-01-19 00:05
A simpler version, that we ran into repeatedly in case studies:
```java
public class DeviationRenderer {
  public void drawItem(XYDataset dataset,
    int series,
    @IndexFor("#1.getSeries(#3)") int item) {
    if (*) {
      IntervalXYDataset intervalDataset =
        (IntervalXYDataset) dataset;
      // Index Checker error on next line
      double x =
        intervalDataset.getXValue(series, item);
    ...

public class IntervalXYDataset {
  public double getXValue(int series, @IndexFor(this.getSeries(#1))) {
  ...
```

**Comment by kelloggm** [comment] 2018-01-19 00:06
Issue was closed via fat fingering. Reopening.

**Comment by smillst** [comment] 2018-01-19 19:56
@kelloggm Your example is a problem for arrays, too.  For example:
```
import org.checkerframework.checker.index.qual.IndexFor;
public class SameLenCustom {
    abstract static class XYDataset {
        abstract public int[] getSeries(int item);
    }

    abstract class IntervalXYDataset extends XYDataset {
       abstract  double getXValue(int series, @IndexFor("this.getSeries(#1)") int p);
    }

    public void drawItem(XYDataset dataset, int series,
            @IndexFor("#1.getSeries(#3)") int item) {
            IntervalXYDataset intervalDataset = (IntervalXYDataset) dataset;
            // Index Checker error on next line, but intervalDataset should be @SameLen("dataset")
            double x = intervalDataset.getXValue(series, item);
    }
}
```
produces:

```
SameLenCustom.java:17: error: [argument.type.incompatible] incompatible types in argument.
            double x = intervalDataset.getXValue(series, item);
                                                         ^
  found   : @LTLengthOf(value="dataset.getSeries(item)", offset={}) int
  required: @LTLengthOf(value="intervalDataset.getSeries(series)", offset={}) int
1 error
```

The problem is that the UpperBound checker doesn't know that `dataset` and `intervalDataset` reference the same object.

**Closed** 2018-01-22 19:27 UTC
